env: dev
port: 9999
database:
  master:
    username: admin
    password: admin
    dbName: local
    host: localhost
    port: 5432
  slave:
    username: admin
    password: admin
    dbName: local
    host: localhost
    port: 5432
redis:
  addr: localhost:6379
  password: ""
  db: 0
kafka:     
  brokers:
    - localhost:9092
  topic: dev_topic
